# Generated by Django 4.2.5 on 2023-09-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChlorineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Uid', models.CharField(max_length=20)),
                ('Pwd', models.CharField(max_length=10)),
            ],
        ),
    ]
